version: '3'

services:
  conversation-orchestrator:
    build:
      context: ./orchestrator
    container_name: conversation-orchestrator
    volumes:
      - ./conversations:/app/conversations
      - ./characters:/app/characters
      - ./config:/app/config
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434/api
    restart: unless-stopped

  web-ui:
    build:
      context: ./web-ui
    container_name: conversation-ui
    ports:
      - "3000:3000"
    depends_on:
      - conversation-orchestrator
    restart: unless-stopped
